./convertfix.sh caxpy.f
./convertfix.sh cbbcsd.f
./convertfix.sh cbdsqr.f
./convertfix.sh ccopy.f
./convertfix.sh cdotc.f
./convertfix.sh cdotu.f
./convertfix.sh cgbbrd.f
./convertfix.sh cgbcon.f
./convertfix.sh cgbequb.f
./convertfix.sh cgbequ.f
./convertfix.sh cgbmv.f
./convertfix.sh cgbrfs.f
./convertfix.sh cgbrfsx.f
./convertfix.sh cgbsv.f
./convertfix.sh cgbsvx.f
./convertfix.sh cgbsvxx.f
./convertfix.sh cgbtf2.f
./convertfix.sh cgbtrf.f
./convertfix.sh cgbtrs.f
./convertfix.sh cgebak.f
./convertfix.sh cgebal.f
./convertfix.sh cgebd2.f
./convertfix.sh cgebrd.f
./convertfix.sh cgecon.f
./convertfix.sh cgeequb.f
./convertfix.sh cgeequ.f
./convertfix.sh cgees.f
./convertfix.sh cgeesx.f
./convertfix.sh cgeev.f
./convertfix.sh cgeevx.f
./convertfix.sh cgehd2.f
./convertfix.sh cgehrd.f
./convertfix.sh cgejsv.f
./convertfix.sh cgelq2.f
./convertfix.sh cgelq.f
./convertfix.sh cgelqf.f
./convertfix.sh cgelqt3.f
./convertfix.sh cgelqt.f
./convertfix.sh cgelsd.f
./convertfix.sh cgels.f
./convertfix.sh cgelss.f
./convertfix.sh cgelsy.f
./convertfix.sh cgemlq.f
./convertfix.sh cgemlqt.f
./convertfix.sh cgemm.f
./convertfix.sh cgemqr.f
./convertfix.sh cgemqrt.f
./convertfix.sh cgemv.f
./convertfix.sh cgeql2.f
./convertfix.sh cgeqlf.f
./convertfix.sh cgeqp3.f
./convertfix.sh cgeqr2.f
./convertfix.sh cgeqr2p.f
./convertfix.sh cgeqr.f
./convertfix.sh cgeqrf.f
./convertfix.sh cgeqrfp.f
./convertfix.sh cgeqrt2.f
./convertfix.sh cgeqrt3.f
./convertfix.sh cgeqrt.f
./convertfix.sh cgerc.f
./convertfix.sh cgerfs.f
./convertfix.sh cgerfsx.f
./convertfix.sh cgerq2.f
./convertfix.sh cgerqf.f
./convertfix.sh cgeru.f
./convertfix.sh cgesc2.f
./convertfix.sh cgesdd.f
./convertfix.sh cgesvd.f
./convertfix.sh cgesvdx.f
./convertfix.sh cgesv.f
./convertfix.sh cgesvj.f
./convertfix.sh cgesvx.f
./convertfix.sh cgesvxx.f
./convertfix.sh cgetc2.f
./convertfix.sh cgetf2.f
./convertfix.sh cgetrf2.f
./convertfix.sh cgetrf.f
./convertfix.sh cgetri.f
./convertfix.sh cgetrs.f
./convertfix.sh cgetsls.f
./convertfix.sh cggbak.f
./convertfix.sh cggbal.f
./convertfix.sh cgges3.f
./convertfix.sh cgges.f
./convertfix.sh cggesx.f
./convertfix.sh cggev3.f
./convertfix.sh cggev.f
./convertfix.sh cggevx.f
./convertfix.sh cggglm.f
./convertfix.sh cgghd3.f
./convertfix.sh cgghrd.f
./convertfix.sh cgglse.f
./convertfix.sh cggqrf.f
./convertfix.sh cggrqf.f
./convertfix.sh cggsvd3.f
./convertfix.sh cggsvp3.f
./convertfix.sh cgsvj0.f
./convertfix.sh cgsvj1.f
./convertfix.sh cgtcon.f
./convertfix.sh cgtrfs.f
./convertfix.sh cgtsv.f
./convertfix.sh cgtsvx.f
./convertfix.sh cgttrf.f
./convertfix.sh cgttrs.f
./convertfix.sh cgtts2.f
./convertfix.sh chb2st_kernels.f
./convertfix.sh chbev_2stage.f
./convertfix.sh chbevd_2stage.f
./convertfix.sh chbevd.f
./convertfix.sh chbev.f
./convertfix.sh chbevx_2stage.f
./convertfix.sh chbevx.f
./convertfix.sh chbgst.f
./convertfix.sh chbgvd.f
./convertfix.sh chbgv.f
./convertfix.sh chbgvx.f
./convertfix.sh chbmv.f
./convertfix.sh chbtrd.f
./convertfix.sh checon_3.f
./convertfix.sh checon.f
./convertfix.sh checon_rook.f
./convertfix.sh cheequb.f
./convertfix.sh cheev_2stage.f
./convertfix.sh cheevd_2stage.f
./convertfix.sh cheevd.f
./convertfix.sh cheev.f
./convertfix.sh cheevr_2stage.f
./convertfix.sh cheevr.f
./convertfix.sh cheevx_2stage.f
./convertfix.sh cheevx.f
./convertfix.sh chegs2.f
./convertfix.sh chegst.f
./convertfix.sh chegv_2stage.f
./convertfix.sh chegvd.f
./convertfix.sh chegv.f
./convertfix.sh chegvx.f
./convertfix.sh chemm.f
./convertfix.sh chemv.f
./convertfix.sh cher2.f
./convertfix.sh cher2k.f
./convertfix.sh cher.f
./convertfix.sh cherfs.f
./convertfix.sh cherfsx.f
./convertfix.sh cherk.f
./convertfix.sh chesv_aa_2stage.f
./convertfix.sh chesv_aa.f
./convertfix.sh chesv.f
./convertfix.sh chesv_rk.f
./convertfix.sh chesv_rook.f
./convertfix.sh chesvx.f
./convertfix.sh chesvxx.f
./convertfix.sh cheswapr.f
./convertfix.sh chetd2.f
./convertfix.sh chetf2.f
./convertfix.sh chetf2_rk.f
./convertfix.sh chetf2_rook.f
./convertfix.sh chetrd_2stage.f
./convertfix.sh chetrd.f
./convertfix.sh chetrd_he2hb.f
./convertfix.sh chetrf_aa_2stage.f
./convertfix.sh chetrf_aa.f
./convertfix.sh chetrf.f
./convertfix.sh chetrf_rk.f
./convertfix.sh chetrf_rook.f
./convertfix.sh chetri2.f
./convertfix.sh chetri2x.f
./convertfix.sh chetri_3.f
./convertfix.sh chetri_3x.f
./convertfix.sh chetri.f
./convertfix.sh chetri_rook.f
./convertfix.sh chetrs2.f
./convertfix.sh chetrs_3.f
./convertfix.sh chetrs_aa_2stage.f
./convertfix.sh chetrs_aa.f
./convertfix.sh chetrs.f
./convertfix.sh chetrs_rook.f
./convertfix.sh chfrk.f
./convertfix.sh chgeqz.f
./convertfix.sh chla_transtype.f
./convertfix.sh chpcon.f
./convertfix.sh chpevd.f
./convertfix.sh chpev.f
./convertfix.sh chpevx.f
./convertfix.sh chpgst.f
./convertfix.sh chpgvd.f
./convertfix.sh chpgv.f
./convertfix.sh chpgvx.f
./convertfix.sh chpmv.f
./convertfix.sh chpr2.f
./convertfix.sh chpr.f
./convertfix.sh chprfs.f
./convertfix.sh chpsv.f
./convertfix.sh chpsvx.f
./convertfix.sh chptrd.f
./convertfix.sh chptrf.f
./convertfix.sh chptri.f
./convertfix.sh chptrs.f
./convertfix.sh chsein.f
./convertfix.sh chseqr.f
./convertfix.sh clabrd.f
./convertfix.sh clacgv.f
./convertfix.sh clacn2.f
./convertfix.sh clacon.f
./convertfix.sh clacp2.f
./convertfix.sh clacpy.f
./convertfix.sh clacrm.f
./convertfix.sh clacrt.f
./convertfix.sh cladiv.f
./convertfix.sh claed0.f
./convertfix.sh claed7.f
./convertfix.sh claed8.f
./convertfix.sh claein.f
./convertfix.sh claesy.f
./convertfix.sh claev2.f
./convertfix.sh clag2z.f
./convertfix.sh cla_gbamv.f
./convertfix.sh cla_gbrcond_c.f
./convertfix.sh cla_gbrcond_x.f
./convertfix.sh cla_gbrfsx_extended.f
./convertfix.sh cla_gbrpvgrw.f
./convertfix.sh cla_geamv.f
./convertfix.sh cla_gercond_c.f
./convertfix.sh cla_gercond_x.f
./convertfix.sh cla_gerfsx_extended.f
./convertfix.sh cla_gerpvgrw.f
./convertfix.sh clags2.f
./convertfix.sh clagtm.f
./convertfix.sh cla_heamv.f
./convertfix.sh clahef_aa.f
./convertfix.sh clahef.f
./convertfix.sh clahef_rk.f
./convertfix.sh clahef_rook.f
./convertfix.sh cla_hercond_c.f
./convertfix.sh cla_hercond_x.f
./convertfix.sh cla_herfsx_extended.f
./convertfix.sh cla_herpvgrw.f
./convertfix.sh clahqr.f
./convertfix.sh clahr2.f
./convertfix.sh claic1.f
./convertfix.sh cla_lin_berr.f
./convertfix.sh clals0.f
./convertfix.sh clalsa.f
./convertfix.sh clalsd.f
./convertfix.sh clamswlq.f
./convertfix.sh clamtsqr.f
./convertfix.sh clangb.f
./convertfix.sh clange.f
./convertfix.sh clangt.f
./convertfix.sh clanhb.f
./convertfix.sh clanhe.f
./convertfix.sh clanhf.f
./convertfix.sh clanhp.f
./convertfix.sh clanhs.f
./convertfix.sh clanht.f
./convertfix.sh clansb.f
./convertfix.sh clansp.f
./convertfix.sh clansy.f
./convertfix.sh clantb.f
./convertfix.sh clantp.f
./convertfix.sh clantr.f
./convertfix.sh clapll.f
./convertfix.sh clapmr.f
./convertfix.sh clapmt.f
./convertfix.sh cla_porcond_c.f
./convertfix.sh cla_porcond_x.f
./convertfix.sh cla_porfsx_extended.f
./convertfix.sh cla_porpvgrw.f
./convertfix.sh claqgb.f
./convertfix.sh claqge.f
./convertfix.sh claqhb.f
./convertfix.sh claqhe.f
./convertfix.sh claqhp.f
./convertfix.sh claqp2.f
./convertfix.sh claqps.f
./convertfix.sh claqr0.f
./convertfix.sh claqr1.f
./convertfix.sh claqr2.f
./convertfix.sh claqr3.f
./convertfix.sh claqr4.f
./convertfix.sh claqr5.f
./convertfix.sh claqsb.f
./convertfix.sh claqsp.f
./convertfix.sh claqsy.f
./convertfix.sh clar1v.f
./convertfix.sh clar2v.f
./convertfix.sh clarcm.f
./convertfix.sh clarfb.f
./convertfix.sh clarf.f
./convertfix.sh clarfg.f
./convertfix.sh clarfgp.f
./convertfix.sh clarft.f
./convertfix.sh clarfx.f
./convertfix.sh clarfy.f
./convertfix.sh clargv.f
./convertfix.sh clarnv.f
./convertfix.sh clarrv.f
./convertfix.sh clarscl2.f
./convertfix.sh clartg.f
./convertfix.sh clartv.f
./convertfix.sh clarzb.f
./convertfix.sh clarz.f
./convertfix.sh clarzt.f
./convertfix.sh clascl2.f
./convertfix.sh clascl.f
./convertfix.sh claset.f
./convertfix.sh clasr.f
./convertfix.sh classq.f
./convertfix.sh claswlq.f
./convertfix.sh claswp.f
./convertfix.sh cla_syamv.f
./convertfix.sh clasyf_aa.f
./convertfix.sh clasyf.f
./convertfix.sh clasyf_rk.f
./convertfix.sh clasyf_rook.f
./convertfix.sh cla_syrcond_c.f
./convertfix.sh cla_syrcond_x.f
./convertfix.sh cla_syrfsx_extended.f
./convertfix.sh cla_syrpvgrw.f
./convertfix.sh clatbs.f
./convertfix.sh clatdf.f
./convertfix.sh clatps.f
./convertfix.sh clatrd.f
./convertfix.sh clatrs.f
./convertfix.sh clatrz.f
./convertfix.sh clatsqr.f
./convertfix.sh clauu2.f
./convertfix.sh clauum.f
./convertfix.sh cla_wwaddw.f
./convertfix.sh cpbcon.f
./convertfix.sh cpbequ.f
./convertfix.sh cpbrfs.f
./convertfix.sh cpbstf.f
./convertfix.sh cpbsv.f
./convertfix.sh cpbsvx.f
./convertfix.sh cpbtf2.f
./convertfix.sh cpbtrf.f
./convertfix.sh cpbtrs.f
./convertfix.sh cpftrf.f
./convertfix.sh cpftri.f
./convertfix.sh cpftrs.f
./convertfix.sh cpocon.f
./convertfix.sh cpoequb.f
./convertfix.sh cpoequ.f
./convertfix.sh cporfs.f
./convertfix.sh cporfsx.f
./convertfix.sh cposv.f
./convertfix.sh cposvx.f
./convertfix.sh cposvxx.f
./convertfix.sh cpotf2.f
./convertfix.sh cpotrf2.f
./convertfix.sh cpotrf.f
./convertfix.sh cpotri.f
./convertfix.sh cpotrs.f
./convertfix.sh cppcon.f
./convertfix.sh cppequ.f
./convertfix.sh cpprfs.f
./convertfix.sh cppsv.f
./convertfix.sh cppsvx.f
./convertfix.sh cpptrf.f
./convertfix.sh cpptri.f
./convertfix.sh cpptrs.f
./convertfix.sh cpstf2.f
./convertfix.sh cpstrf.f
./convertfix.sh cptcon.f
./convertfix.sh cpteqr.f
./convertfix.sh cptrfs.f
./convertfix.sh cptsv.f
./convertfix.sh cptsvx.f
./convertfix.sh cpttrf.f
./convertfix.sh cpttrs.f
./convertfix.sh cptts2.f
./convertfix.sh crot.f
./convertfix.sh crotg.f
./convertfix.sh cscal.f
./convertfix.sh cspcon.f
./convertfix.sh cspmv.f
./convertfix.sh cspr.f
./convertfix.sh csprfs.f
./convertfix.sh cspsv.f
./convertfix.sh cspsvx.f
./convertfix.sh csptrf.f
./convertfix.sh csptri.f
./convertfix.sh csptrs.f
./convertfix.sh csrot.f
./convertfix.sh csrscl.f
./convertfix.sh csscal.f
./convertfix.sh cstedc.f
./convertfix.sh cstegr.f
./convertfix.sh cstein.f
./convertfix.sh cstemr.f
./convertfix.sh csteqr.f
./convertfix.sh cswap.f
./convertfix.sh csycon_3.f
./convertfix.sh csycon.f
./convertfix.sh csycon_rook.f
./convertfix.sh csyconv.f
./convertfix.sh csyconvf.f
./convertfix.sh csyconvf_rook.f
./convertfix.sh csyequb.f
./convertfix.sh csymm.f
./convertfix.sh csymv.f
./convertfix.sh csyr2k.f
./convertfix.sh csyr.f
./convertfix.sh csyrfs.f
./convertfix.sh csyrfsx.f
./convertfix.sh csyrk.f
./convertfix.sh csysv_aa_2stage.f
./convertfix.sh csysv_aa.f
./convertfix.sh csysv.f
./convertfix.sh csysv_rk.f
./convertfix.sh csysv_rook.f
./convertfix.sh csysvx.f
./convertfix.sh csysvxx.f
./convertfix.sh csyswapr.f
./convertfix.sh csytf2.f
./convertfix.sh csytf2_rk.f
./convertfix.sh csytf2_rook.f
./convertfix.sh csytrf_aa_2stage.f
./convertfix.sh csytrf_aa.f
./convertfix.sh csytrf.f
./convertfix.sh csytrf_rk.f
./convertfix.sh csytrf_rook.f
./convertfix.sh csytri2.f
./convertfix.sh csytri2x.f
./convertfix.sh csytri_3.f
./convertfix.sh csytri_3x.f
./convertfix.sh csytri.f
./convertfix.sh csytri_rook.f
./convertfix.sh csytrs2.f
./convertfix.sh csytrs_3.f
./convertfix.sh csytrs_aa_2stage.f
./convertfix.sh csytrs_aa.f
./convertfix.sh csytrs.f
./convertfix.sh csytrs_rook.f
./convertfix.sh ctbcon.f
./convertfix.sh ctbmv.f
./convertfix.sh ctbrfs.f
./convertfix.sh ctbsv.f
./convertfix.sh ctbtrs.f
./convertfix.sh ctfsm.f
./convertfix.sh ctftri.f
./convertfix.sh ctfttp.f
./convertfix.sh ctfttr.f
./convertfix.sh ctgevc.f
./convertfix.sh ctgex2.f
./convertfix.sh ctgexc.f
./convertfix.sh ctgsen.f
./convertfix.sh ctgsja.f
./convertfix.sh ctgsna.f
./convertfix.sh ctgsy2.f
./convertfix.sh ctgsyl.f
./convertfix.sh ctpcon.f
./convertfix.sh ctplqt2.f
./convertfix.sh ctplqt.f
./convertfix.sh ctpmlqt.f
./convertfix.sh ctpmqrt.f
./convertfix.sh ctpmv.f
./convertfix.sh ctpqrt2.f
./convertfix.sh ctpqrt.f
./convertfix.sh ctprfb.f
./convertfix.sh ctprfs.f
./convertfix.sh ctpsv.f
./convertfix.sh ctptri.f
./convertfix.sh ctptrs.f
./convertfix.sh ctpttf.f
./convertfix.sh ctpttr.f
./convertfix.sh ctrcon.f
./convertfix.sh ctrevc3.f
./convertfix.sh ctrevc.f
./convertfix.sh ctrexc.f
./convertfix.sh ctrmm.f
./convertfix.sh ctrmv.f
./convertfix.sh ctrrfs.f
./convertfix.sh ctrsen.f
./convertfix.sh ctrsm.f
./convertfix.sh ctrsna.f
./convertfix.sh ctrsv.f
./convertfix.sh ctrsyl.f
./convertfix.sh ctrti2.f
./convertfix.sh ctrtri.f
./convertfix.sh ctrtrs.f
./convertfix.sh ctrttf.f
./convertfix.sh ctrttp.f
./convertfix.sh ctzrzf.f
./convertfix.sh cunbdb1.f
./convertfix.sh cunbdb2.f
./convertfix.sh cunbdb3.f
./convertfix.sh cunbdb4.f
./convertfix.sh cunbdb5.f
./convertfix.sh cunbdb6.f
./convertfix.sh cunbdb.f
./convertfix.sh cuncsd2by1.f
./convertfix.sh cuncsd.f
./convertfix.sh cung2l.f
./convertfix.sh cung2r.f
./convertfix.sh cungbr.f
./convertfix.sh cunghr.f
./convertfix.sh cungl2.f
./convertfix.sh cunglq.f
./convertfix.sh cungql.f
./convertfix.sh cungqr.f
./convertfix.sh cungr2.f
./convertfix.sh cungrq.f
./convertfix.sh cungtr.f
./convertfix.sh cunm22.f
./convertfix.sh cunm2l.f
./convertfix.sh cunm2r.f
./convertfix.sh cunmbr.f
./convertfix.sh cunmhr.f
./convertfix.sh cunml2.f
./convertfix.sh cunmlq.f
./convertfix.sh cunmql.f
./convertfix.sh cunmqr.f
./convertfix.sh cunmr2.f
./convertfix.sh cunmr3.f
./convertfix.sh cunmrq.f
./convertfix.sh cunmrz.f
./convertfix.sh cunmtr.f
./convertfix.sh cupgtr.f
./convertfix.sh cupmtr.f
./convertfix.sh dasum.f
./convertfix.sh daxpy.f
./convertfix.sh dbbcsd.f
./convertfix.sh dbdsdc.f
./convertfix.sh dbdsqr.f
./convertfix.sh dbdsvdx.f
./convertfix.sh dcabs1.f
./convertfix.sh dcopy.f
./convertfix.sh ddisna.f
./convertfix.sh ddot.f
./convertfix.sh dgbbrd.f
./convertfix.sh dgbcon.f
./convertfix.sh dgbequb.f
./convertfix.sh dgbequ.f
./convertfix.sh dgbmv.f
./convertfix.sh dgbrfs.f
./convertfix.sh dgbrfsx.f
./convertfix.sh dgbsv.f
./convertfix.sh dgbsvx.f
./convertfix.sh dgbsvxx.f
./convertfix.sh dgbtf2.f
./convertfix.sh dgbtrf.f
./convertfix.sh dgbtrs.f
./convertfix.sh dgebak.f
./convertfix.sh dgebal.f
./convertfix.sh dgebd2.f
./convertfix.sh dgebrd.f
./convertfix.sh dgecon.f
./convertfix.sh dgeequb.f
./convertfix.sh dgeequ.f
./convertfix.sh dgees.f
./convertfix.sh dgeesx.f
./convertfix.sh dgeev.f
./convertfix.sh dgeevx.f
./convertfix.sh dgehd2.f
./convertfix.sh dgehrd.f
./convertfix.sh dgejsv.f
./convertfix.sh dgelq2.f
./convertfix.sh dgelq.f
./convertfix.sh dgelqf.f
./convertfix.sh dgelqt3.f
./convertfix.sh dgelqt.f
./convertfix.sh dgelsd.f
./convertfix.sh dgels.f
./convertfix.sh dgelss.f
./convertfix.sh dgelsy.f
./convertfix.sh dgemlq.f
./convertfix.sh dgemlqt.f
./convertfix.sh dgemm.f
./convertfix.sh dgemqr.f
./convertfix.sh dgemqrt.f
./convertfix.sh dgemv.f
./convertfix.sh dgeql2.f
./convertfix.sh dgeqlf.f
./convertfix.sh dgeqp3.f
./convertfix.sh dgeqr2.f
./convertfix.sh dgeqr2p.f
./convertfix.sh dgeqr.f
./convertfix.sh dgeqrf.f
./convertfix.sh dgeqrfp.f
./convertfix.sh dgeqrt2.f
./convertfix.sh dgeqrt3.f
./convertfix.sh dgeqrt.f
./convertfix.sh dger.f
./convertfix.sh dgerfs.f
./convertfix.sh dgerfsx.f
./convertfix.sh dgerq2.f
./convertfix.sh dgerqf.f
./convertfix.sh dgesc2.f
./convertfix.sh dgesdd.f
./convertfix.sh dgesvd.f
./convertfix.sh dgesvdx.f
./convertfix.sh dgesv.f
./convertfix.sh dgesvj.f
./convertfix.sh dgesvx.f
./convertfix.sh dgesvxx.f
./convertfix.sh dgetc2.f
./convertfix.sh dgetf2.f
./convertfix.sh dgetrf2.f
./convertfix.sh dgetrf.f
./convertfix.sh dgetri.f
./convertfix.sh dgetrs.f
./convertfix.sh dgetsls.f
./convertfix.sh dggbak.f
./convertfix.sh dggbal.f
./convertfix.sh dgges3.f
./convertfix.sh dgges.f
./convertfix.sh dggesx.f
./convertfix.sh dggev3.f
./convertfix.sh dggev.f
./convertfix.sh dggevx.f
./convertfix.sh dggglm.f
./convertfix.sh dgghd3.f
./convertfix.sh dgghrd.f
./convertfix.sh dgglse.f
./convertfix.sh dggqrf.f
./convertfix.sh dggrqf.f
./convertfix.sh dggsvd3.f
./convertfix.sh dggsvp3.f
./convertfix.sh dgsvj0.f
./convertfix.sh dgsvj1.f
./convertfix.sh dgtcon.f
./convertfix.sh dgtrfs.f
./convertfix.sh dgtsv.f
./convertfix.sh dgtsvx.f
./convertfix.sh dgttrf.f
./convertfix.sh dgttrs.f
./convertfix.sh dgtts2.f
./convertfix.sh dhgeqz.f
./convertfix.sh dhsein.f
./convertfix.sh dhseqr.f
./convertfix.sh disnan.f
./convertfix.sh dlabad.f
./convertfix.sh dlabrd.f
./convertfix.sh dlacn2.f
./convertfix.sh dlacon.f
./convertfix.sh dlacpy.f
./convertfix.sh dladiv.f
./convertfix.sh dlae2.f
./convertfix.sh dlaebz.f
./convertfix.sh dlaed0.f
./convertfix.sh dlaed1.f
./convertfix.sh dlaed2.f
./convertfix.sh dlaed3.f
./convertfix.sh dlaed4.f
./convertfix.sh dlaed5.f
./convertfix.sh dlaed6.f
./convertfix.sh dlaed7.f
./convertfix.sh dlaed8.f
./convertfix.sh dlaed9.f
./convertfix.sh dlaeda.f
./convertfix.sh dlaein.f
./convertfix.sh dlaev2.f
./convertfix.sh dlaexc.f
./convertfix.sh dlag2.f
./convertfix.sh dlag2s.f
./convertfix.sh dla_gbamv.f
./convertfix.sh dla_gbrcond.f
./convertfix.sh dla_gbrfsx_extended.f
./convertfix.sh dla_gbrpvgrw.f
./convertfix.sh dla_geamv.f
./convertfix.sh dla_gercond.f
./convertfix.sh dla_gerfsx_extended.f
./convertfix.sh dla_gerpvgrw.f
./convertfix.sh dlags2.f
./convertfix.sh dlagtf.f
./convertfix.sh dlagtm.f
./convertfix.sh dlagts.f
./convertfix.sh dlagv2.f
./convertfix.sh dlahqr.f
./convertfix.sh dlahr2.f
./convertfix.sh dlaic1.f
./convertfix.sh dlaisnan.f
./convertfix.sh dla_lin_berr.f
./convertfix.sh dlaln2.f
./convertfix.sh dlals0.f
./convertfix.sh dlalsa.f
./convertfix.sh dlalsd.f
./convertfix.sh dlamrg.f
./convertfix.sh dlamswlq.f
./convertfix.sh dlamtsqr.f
./convertfix.sh dlaneg.f
./convertfix.sh dlangb.f
./convertfix.sh dlange.f
./convertfix.sh dlangt.f
./convertfix.sh dlanhs.f
./convertfix.sh dlansb.f
./convertfix.sh dlansf.f
./convertfix.sh dlansp.f
./convertfix.sh dlanst.f
./convertfix.sh dlansy.f
./convertfix.sh dlantb.f
./convertfix.sh dlantp.f
./convertfix.sh dlantr.f
./convertfix.sh dlanv2.f
./convertfix.sh dlapll.f
./convertfix.sh dlapmr.f
./convertfix.sh dlapmt.f
./convertfix.sh dla_porcond.f
./convertfix.sh dla_porfsx_extended.f
./convertfix.sh dla_porpvgrw.f
./convertfix.sh dlapy2.f
./convertfix.sh dlapy3.f
./convertfix.sh dlaqgb.f
./convertfix.sh dlaqge.f
./convertfix.sh dlaqp2.f
./convertfix.sh dlaqps.f
./convertfix.sh dlaqr0.f
./convertfix.sh dlaqr1.f
./convertfix.sh dlaqr2.f
./convertfix.sh dlaqr3.f
./convertfix.sh dlaqr4.f
./convertfix.sh dlaqr5.f
./convertfix.sh dlaqsb.f
./convertfix.sh dlaqsp.f
./convertfix.sh dlaqsy.f
./convertfix.sh dlaqtr.f
./convertfix.sh dlar1v.f
./convertfix.sh dlar2v.f
./convertfix.sh dlarfb.f
./convertfix.sh dlarf.f
./convertfix.sh dlarfg.f
./convertfix.sh dlarfgp.f
./convertfix.sh dlarft.f
./convertfix.sh dlarfx.f
./convertfix.sh dlarfy.f
./convertfix.sh dlargv.f
./convertfix.sh dlarnv.f
./convertfix.sh dlarra.f
./convertfix.sh dlarrb.f
./convertfix.sh dlarrc.f
./convertfix.sh dlarrd.f
./convertfix.sh dlarre.f
./convertfix.sh dlarrf.f
./convertfix.sh dlarrj.f
./convertfix.sh dlarrk.f
./convertfix.sh dlarrr.f
./convertfix.sh dlarrv.f
./convertfix.sh dlarscl2.f
./convertfix.sh dlartg.f
./convertfix.sh dlartgp.f
./convertfix.sh dlartgs.f
./convertfix.sh dlartv.f
./convertfix.sh dlaruv.f
./convertfix.sh dlarzb.f
./convertfix.sh dlarz.f
./convertfix.sh dlarzt.f
./convertfix.sh dlas2.f
./convertfix.sh dlascl2.f
./convertfix.sh dlascl.f
./convertfix.sh dlasd0.f
./convertfix.sh dlasd1.f
./convertfix.sh dlasd2.f
./convertfix.sh dlasd3.f
./convertfix.sh dlasd4.f
./convertfix.sh dlasd5.f
./convertfix.sh dlasd6.f
./convertfix.sh dlasd7.f
./convertfix.sh dlasd8.f
./convertfix.sh dlasda.f
./convertfix.sh dlasdq.f
./convertfix.sh dlasdt.f
./convertfix.sh dlaset.f
./convertfix.sh dlasq1.f
./convertfix.sh dlasq2.f
./convertfix.sh dlasq3.f
./convertfix.sh dlasq4.f
./convertfix.sh dlasq5.f
./convertfix.sh dlasq6.f
./convertfix.sh dlasr.f
./convertfix.sh dlasrt.f
./convertfix.sh dlassq.f
./convertfix.sh dlasv2.f
./convertfix.sh dlaswlq.f
./convertfix.sh dlaswp.f
./convertfix.sh dlasy2.f
./convertfix.sh dla_syamv.f
./convertfix.sh dlasyf_aa.f
./convertfix.sh dlasyf.f
./convertfix.sh dlasyf_rk.f
./convertfix.sh dlasyf_rook.f
./convertfix.sh dla_syrcond.f
./convertfix.sh dla_syrfsx_extended.f
./convertfix.sh dla_syrpvgrw.f
./convertfix.sh dlat2s.f
./convertfix.sh dlatbs.f
./convertfix.sh dlatdf.f
./convertfix.sh dlatps.f
./convertfix.sh dlatrd.f
./convertfix.sh dlatrs.f
./convertfix.sh dlatrz.f
./convertfix.sh dlatsqr.f
./convertfix.sh dlauu2.f
./convertfix.sh dlauum.f
./convertfix.sh dla_wwaddw.f
./convertfix.sh dnrm2.f
./convertfix.sh dopgtr.f
./convertfix.sh dopmtr.f
./convertfix.sh dorbdb1.f
./convertfix.sh dorbdb2.f
./convertfix.sh dorbdb3.f
./convertfix.sh dorbdb4.f
./convertfix.sh dorbdb5.f
./convertfix.sh dorbdb6.f
./convertfix.sh dorbdb.f
./convertfix.sh dorcsd2by1.f
./convertfix.sh dorcsd.f
./convertfix.sh dorg2l.f
./convertfix.sh dorg2r.f
./convertfix.sh dorgbr.f
./convertfix.sh dorghr.f
./convertfix.sh dorgl2.f
./convertfix.sh dorglq.f
./convertfix.sh dorgql.f
./convertfix.sh dorgqr.f
./convertfix.sh dorgr2.f
./convertfix.sh dorgrq.f
./convertfix.sh dorgtr.f
./convertfix.sh dorm22.f
./convertfix.sh dorm2l.f
./convertfix.sh dorm2r.f
./convertfix.sh dormbr.f
./convertfix.sh dormhr.f
./convertfix.sh dorml2.f
./convertfix.sh dormlq.f
./convertfix.sh dormql.f
./convertfix.sh dormqr.f
./convertfix.sh dormr2.f
./convertfix.sh dormr3.f
./convertfix.sh dormrq.f
./convertfix.sh dormrz.f
./convertfix.sh dormtr.f
./convertfix.sh dpbcon.f
./convertfix.sh dpbequ.f
./convertfix.sh dpbrfs.f
./convertfix.sh dpbstf.f
./convertfix.sh dpbsv.f
./convertfix.sh dpbsvx.f
./convertfix.sh dpbtf2.f
./convertfix.sh dpbtrf.f
./convertfix.sh dpbtrs.f
./convertfix.sh dpftrf.f
./convertfix.sh dpftri.f
./convertfix.sh dpftrs.f
./convertfix.sh dpocon.f
./convertfix.sh dpoequb.f
./convertfix.sh dpoequ.f
./convertfix.sh dporfs.f
./convertfix.sh dporfsx.f
./convertfix.sh dposv.f
./convertfix.sh dposvx.f
./convertfix.sh dposvxx.f
./convertfix.sh dpotf2.f
./convertfix.sh dpotrf2.f
./convertfix.sh dpotrf.f
./convertfix.sh dpotri.f
./convertfix.sh dpotrs.f
./convertfix.sh dppcon.f
./convertfix.sh dppequ.f
./convertfix.sh dpprfs.f
./convertfix.sh dppsv.f
./convertfix.sh dppsvx.f
./convertfix.sh dpptrf.f
./convertfix.sh dpptri.f
./convertfix.sh dpptrs.f
./convertfix.sh dpstf2.f
./convertfix.sh dpstrf.f
./convertfix.sh dptcon.f
./convertfix.sh dpteqr.f
./convertfix.sh dptrfs.f
./convertfix.sh dptsv.f
./convertfix.sh dptsvx.f
./convertfix.sh dpttrf.f
./convertfix.sh dpttrs.f
./convertfix.sh dptts2.f
./convertfix.sh drot.f
./convertfix.sh drotg.f
./convertfix.sh drotm.f
./convertfix.sh drotmg.f
./convertfix.sh drscl.f
./convertfix.sh dsb2st_kernels.f
./convertfix.sh dsbev_2stage.f
./convertfix.sh dsbevd_2stage.f
./convertfix.sh dsbevd.f
./convertfix.sh dsbev.f
./convertfix.sh dsbevx_2stage.f
./convertfix.sh dsbevx.f
./convertfix.sh dsbgst.f
./convertfix.sh dsbgvd.f
./convertfix.sh dsbgv.f
./convertfix.sh dsbgvx.f
./convertfix.sh dsbmv.f
./convertfix.sh dsbtrd.f
./convertfix.sh dscal.f
./convertfix.sh dsdot.f
./convertfix.sh dsfrk.f
./convertfix.sh dsgesv.f
./convertfix.sh dspcon.f
./convertfix.sh dspevd.f
./convertfix.sh dspev.f
./convertfix.sh dspevx.f
./convertfix.sh dspgst.f
./convertfix.sh dspgvd.f
./convertfix.sh dspgv.f
./convertfix.sh dspgvx.f
./convertfix.sh dspmv.f
./convertfix.sh dsposv.f
./convertfix.sh dspr2.f
./convertfix.sh dspr.f
./convertfix.sh dsprfs.f
./convertfix.sh dspsv.f
./convertfix.sh dspsvx.f
./convertfix.sh dsptrd.f
./convertfix.sh dsptrf.f
./convertfix.sh dsptri.f
./convertfix.sh dsptrs.f
./convertfix.sh dstebz.f
./convertfix.sh dstedc.f
./convertfix.sh dstegr.f
./convertfix.sh dstein.f
./convertfix.sh dstemr.f
./convertfix.sh dsteqr.f
./convertfix.sh dsterf.f
./convertfix.sh dstevd.f
./convertfix.sh dstev.f
./convertfix.sh dstevr.f
./convertfix.sh dstevx.f
./convertfix.sh dswap.f
./convertfix.sh dsycon_3.f
./convertfix.sh dsycon.f
./convertfix.sh dsycon_rook.f
./convertfix.sh dsyconv.f
./convertfix.sh dsyconvf.f
./convertfix.sh dsyconvf_rook.f
./convertfix.sh dsyequb.f
./convertfix.sh dsyev_2stage.f
./convertfix.sh dsyevd_2stage.f
./convertfix.sh dsyevd.f
./convertfix.sh dsyev.f
./convertfix.sh dsyevr_2stage.f
./convertfix.sh dsyevr.f
./convertfix.sh dsyevx_2stage.f
./convertfix.sh dsyevx.f
./convertfix.sh dsygs2.f
./convertfix.sh dsygst.f
./convertfix.sh dsygv_2stage.f
./convertfix.sh dsygvd.f
./convertfix.sh dsygv.f
./convertfix.sh dsygvx.f
./convertfix.sh dsymm.f
./convertfix.sh dsymv.f
./convertfix.sh dsyr2.f
./convertfix.sh dsyr2k.f
./convertfix.sh dsyr.f
./convertfix.sh dsyrfs.f
./convertfix.sh dsyrfsx.f
./convertfix.sh dsyrk.f
./convertfix.sh dsysv_aa_2stage.f
./convertfix.sh dsysv_aa.f
./convertfix.sh dsysv.f
./convertfix.sh dsysv_rk.f
./convertfix.sh dsysv_rook.f
./convertfix.sh dsysvx.f
./convertfix.sh dsysvxx.f
./convertfix.sh dsyswapr.f
./convertfix.sh dsytd2.f
./convertfix.sh dsytf2.f
./convertfix.sh dsytf2_rk.f
./convertfix.sh dsytf2_rook.f
./convertfix.sh dsytrd_2stage.f
./convertfix.sh dsytrd.f
./convertfix.sh dsytrd_sy2sb.f
./convertfix.sh dsytrf_aa_2stage.f
./convertfix.sh dsytrf_aa.f
./convertfix.sh dsytrf.f
./convertfix.sh dsytrf_rk.f
./convertfix.sh dsytrf_rook.f
./convertfix.sh dsytri2.f
./convertfix.sh dsytri2x.f
./convertfix.sh dsytri_3.f
./convertfix.sh dsytri_3x.f
./convertfix.sh dsytri.f
./convertfix.sh dsytri_rook.f
./convertfix.sh dsytrs2.f
./convertfix.sh dsytrs_3.f
./convertfix.sh dsytrs_aa_2stage.f
./convertfix.sh dsytrs_aa.f
./convertfix.sh dsytrs.f
./convertfix.sh dsytrs_rook.f
./convertfix.sh dtbcon.f
./convertfix.sh dtbmv.f
./convertfix.sh dtbrfs.f
./convertfix.sh dtbsv.f
./convertfix.sh dtbtrs.f
./convertfix.sh dtfsm.f
./convertfix.sh dtftri.f
./convertfix.sh dtfttp.f
./convertfix.sh dtfttr.f
./convertfix.sh dtgevc.f
./convertfix.sh dtgex2.f
./convertfix.sh dtgexc.f
./convertfix.sh dtgsen.f
./convertfix.sh dtgsja.f
./convertfix.sh dtgsna.f
./convertfix.sh dtgsy2.f
./convertfix.sh dtgsyl.f
./convertfix.sh dtpcon.f
./convertfix.sh dtplqt2.f
./convertfix.sh dtplqt.f
./convertfix.sh dtpmlqt.f
./convertfix.sh dtpmqrt.f
./convertfix.sh dtpmv.f
./convertfix.sh dtpqrt2.f
./convertfix.sh dtpqrt.f
./convertfix.sh dtprfb.f
./convertfix.sh dtprfs.f
./convertfix.sh dtpsv.f
./convertfix.sh dtptri.f
./convertfix.sh dtptrs.f
./convertfix.sh dtpttf.f
./convertfix.sh dtpttr.f
./convertfix.sh dtrcon.f
./convertfix.sh dtrevc3.f
./convertfix.sh dtrevc.f
./convertfix.sh dtrexc.f
./convertfix.sh dtrmm.f
./convertfix.sh dtrmv.f
./convertfix.sh dtrrfs.f
./convertfix.sh dtrsen.f
./convertfix.sh dtrsm.f
./convertfix.sh dtrsna.f
./convertfix.sh dtrsv.f
./convertfix.sh dtrsyl.f
./convertfix.sh dtrti2.f
./convertfix.sh dtrtri.f
./convertfix.sh dtrtrs.f
./convertfix.sh dtrttf.f
./convertfix.sh dtrttp.f
./convertfix.sh dtzrzf.f
./convertfix.sh dzasum.f
./convertfix.sh dznrm2.f
./convertfix.sh dzsum1.f
./convertfix.sh fake_xerbla.f
./convertfix.sh icamax.f
./convertfix.sh icmax1.f
./convertfix.sh idamax.f
./convertfix.sh ieeeck.f
./convertfix.sh ilaclc.f
./convertfix.sh ilaclr.f
./convertfix.sh iladiag.f
./convertfix.sh iladlc.f
./convertfix.sh iladlr.f
./convertfix.sh ilaenv2stage.f
./convertfix.sh ilaenv.f
./convertfix.sh ilaprec.f
./convertfix.sh ilaslc.f
./convertfix.sh ilaslr.f
./convertfix.sh ilatrans.f
./convertfix.sh ilauplo.f
./convertfix.sh ilazlc.f
./convertfix.sh ilazlr.f
./convertfix.sh iparmq.f
./convertfix.sh isamax.f
./convertfix.sh izamax.f
./convertfix.sh izmax1.f
./convertfix.sh lsame.f
./convertfix.sh lsamen.f
./convertfix.sh sasum.f
./convertfix.sh saxpy.f
./convertfix.sh sbbcsd.f
./convertfix.sh sbdsdc.f
./convertfix.sh sbdsqr.f
./convertfix.sh sbdsvdx.f
./convertfix.sh scabs1.f
./convertfix.sh scasum.f
./convertfix.sh scnrm2.f
./convertfix.sh scopy.f
./convertfix.sh scsum1.f
./convertfix.sh sdisna.f
./convertfix.sh sdot.f
./convertfix.sh sdsdot.f
./convertfix.sh sgbbrd.f
./convertfix.sh sgbcon.f
./convertfix.sh sgbequb.f
./convertfix.sh sgbequ.f
./convertfix.sh sgbmv.f
./convertfix.sh sgbrfs.f
./convertfix.sh sgbrfsx.f
./convertfix.sh sgbsv.f
./convertfix.sh sgbsvx.f
./convertfix.sh sgbsvxx.f
./convertfix.sh sgbtf2.f
./convertfix.sh sgbtrf.f
./convertfix.sh sgbtrs.f
./convertfix.sh sgebak.f
./convertfix.sh sgebal.f
./convertfix.sh sgebd2.f
./convertfix.sh sgebrd.f
./convertfix.sh sgecon.f
./convertfix.sh sgeequb.f
./convertfix.sh sgeequ.f
./convertfix.sh sgees.f
./convertfix.sh sgeesx.f
./convertfix.sh sgeev.f
./convertfix.sh sgeevx.f
./convertfix.sh sgehd2.f
./convertfix.sh sgehrd.f
./convertfix.sh sgejsv.f
./convertfix.sh sgelq2.f
./convertfix.sh sgelq.f
./convertfix.sh sgelqf.f
./convertfix.sh sgelqt3.f
./convertfix.sh sgelqt.f
./convertfix.sh sgelsd.f
./convertfix.sh sgels.f
./convertfix.sh sgelss.f
./convertfix.sh sgelsy.f
./convertfix.sh sgemlq.f
./convertfix.sh sgemlqt.f
./convertfix.sh sgemm.f
./convertfix.sh sgemqr.f
./convertfix.sh sgemqrt.f
./convertfix.sh sgemv.f
./convertfix.sh sgeql2.f
./convertfix.sh sgeqlf.f
./convertfix.sh sgeqp3.f
./convertfix.sh sgeqr2.f
./convertfix.sh sgeqr2p.f
./convertfix.sh sgeqr.f
./convertfix.sh sgeqrf.f
./convertfix.sh sgeqrfp.f
./convertfix.sh sgeqrt2.f
./convertfix.sh sgeqrt3.f
./convertfix.sh sgeqrt.f
./convertfix.sh sger.f
./convertfix.sh sgerfs.f
./convertfix.sh sgerfsx.f
./convertfix.sh sgerq2.f
./convertfix.sh sgerqf.f
./convertfix.sh sgesc2.f
./convertfix.sh sgesdd.f
./convertfix.sh sgesvd.f
./convertfix.sh sgesvdx.f
./convertfix.sh sgesv.f
./convertfix.sh sgesvj.f
./convertfix.sh sgesvx.f
./convertfix.sh sgesvxx.f
./convertfix.sh sgetc2.f
./convertfix.sh sgetf2.f
./convertfix.sh sgetrf2.f
./convertfix.sh sgetrf.f
./convertfix.sh sgetri.f
./convertfix.sh sgetrs.f
./convertfix.sh sgetsls.f
./convertfix.sh sggbak.f
./convertfix.sh sggbal.f
./convertfix.sh sgges3.f
./convertfix.sh sgges.f
./convertfix.sh sggesx.f
./convertfix.sh sggev3.f
./convertfix.sh sggev.f
./convertfix.sh sggevx.f
./convertfix.sh sggglm.f
./convertfix.sh sgghd3.f
./convertfix.sh sgghrd.f
./convertfix.sh sgglse.f
./convertfix.sh sggqrf.f
./convertfix.sh sggrqf.f
./convertfix.sh sggsvd3.f
./convertfix.sh sggsvp3.f
./convertfix.sh sgsvj0.f
./convertfix.sh sgsvj1.f
./convertfix.sh sgtcon.f
./convertfix.sh sgtrfs.f
./convertfix.sh sgtsv.f
./convertfix.sh sgtsvx.f
./convertfix.sh sgttrf.f
./convertfix.sh sgttrs.f
./convertfix.sh sgtts2.f
./convertfix.sh shgeqz.f
./convertfix.sh shsein.f
./convertfix.sh shseqr.f
./convertfix.sh sisnan.f
./convertfix.sh slabad.f
./convertfix.sh slabrd.f
./convertfix.sh slacn2.f
./convertfix.sh slacon.f
./convertfix.sh slacpy.f
./convertfix.sh sladiv.f
./convertfix.sh slae2.f
./convertfix.sh slaebz.f
./convertfix.sh slaed0.f
./convertfix.sh slaed1.f
./convertfix.sh slaed2.f
./convertfix.sh slaed3.f
./convertfix.sh slaed4.f
./convertfix.sh slaed5.f
./convertfix.sh slaed6.f
./convertfix.sh slaed7.f
./convertfix.sh slaed8.f
./convertfix.sh slaed9.f
./convertfix.sh slaeda.f
./convertfix.sh slaein.f
./convertfix.sh slaev2.f
./convertfix.sh slaexc.f
./convertfix.sh slag2d.f
./convertfix.sh slag2.f
./convertfix.sh sla_gbamv.f
./convertfix.sh sla_gbrcond.f
./convertfix.sh sla_gbrfsx_extended.f
./convertfix.sh sla_gbrpvgrw.f
./convertfix.sh sla_geamv.f
./convertfix.sh sla_gercond.f
./convertfix.sh sla_gerfsx_extended.f
./convertfix.sh sla_gerpvgrw.f
./convertfix.sh slags2.f
./convertfix.sh slagtf.f
./convertfix.sh slagtm.f
./convertfix.sh slagts.f
./convertfix.sh slagv2.f
./convertfix.sh slahqr.f
./convertfix.sh slahr2.f
./convertfix.sh slaic1.f
./convertfix.sh slaisnan.f
./convertfix.sh sla_lin_berr.f
./convertfix.sh slaln2.f
./convertfix.sh slals0.f
./convertfix.sh slalsa.f
./convertfix.sh slalsd.f
./convertfix.sh slamrg.f
./convertfix.sh slamswlq.f
./convertfix.sh slamtsqr.f
./convertfix.sh slaneg.f
./convertfix.sh slangb.f
./convertfix.sh slange.f
./convertfix.sh slangt.f
./convertfix.sh slanhs.f
./convertfix.sh slansb.f
./convertfix.sh slansf.f
./convertfix.sh slansp.f
./convertfix.sh slanst.f
./convertfix.sh slansy.f
./convertfix.sh slantb.f
./convertfix.sh slantp.f
./convertfix.sh slantr.f
./convertfix.sh slanv2.f
./convertfix.sh slapll.f
./convertfix.sh slapmr.f
./convertfix.sh slapmt.f
./convertfix.sh sla_porcond.f
./convertfix.sh sla_porfsx_extended.f
./convertfix.sh sla_porpvgrw.f
./convertfix.sh slapy2.f
./convertfix.sh slapy3.f
./convertfix.sh slaqgb.f
./convertfix.sh slaqge.f
./convertfix.sh slaqp2.f
./convertfix.sh slaqps.f
./convertfix.sh slaqr0.f
./convertfix.sh slaqr1.f
./convertfix.sh slaqr2.f
./convertfix.sh slaqr3.f
./convertfix.sh slaqr4.f
./convertfix.sh slaqr5.f
./convertfix.sh slaqsb.f
./convertfix.sh slaqsp.f
./convertfix.sh slaqsy.f
./convertfix.sh slaqtr.f
./convertfix.sh slar1v.f
./convertfix.sh slar2v.f
./convertfix.sh slarfb.f
./convertfix.sh slarf.f
./convertfix.sh slarfg.f
./convertfix.sh slarfgp.f
./convertfix.sh slarft.f
./convertfix.sh slarfx.f
./convertfix.sh slarfy.f
./convertfix.sh slargv.f
./convertfix.sh slarnv.f
./convertfix.sh slarra.f
./convertfix.sh slarrb.f
./convertfix.sh slarrc.f
./convertfix.sh slarrd.f
./convertfix.sh slarre.f
./convertfix.sh slarrf.f
./convertfix.sh slarrj.f
./convertfix.sh slarrk.f
./convertfix.sh slarrr.f
./convertfix.sh slarrv.f
./convertfix.sh slarscl2.f
./convertfix.sh slartg.f
./convertfix.sh slartgp.f
./convertfix.sh slartgs.f
./convertfix.sh slartv.f
./convertfix.sh slaruv.f
./convertfix.sh slarzb.f
./convertfix.sh slarz.f
./convertfix.sh slarzt.f
./convertfix.sh slas2.f
./convertfix.sh slascl2.f
./convertfix.sh slascl.f
./convertfix.sh slasd0.f
./convertfix.sh slasd1.f
./convertfix.sh slasd2.f
./convertfix.sh slasd3.f
./convertfix.sh slasd4.f
./convertfix.sh slasd5.f
./convertfix.sh slasd6.f
./convertfix.sh slasd7.f
./convertfix.sh slasd8.f
./convertfix.sh slasda.f
./convertfix.sh slasdq.f
./convertfix.sh slasdt.f
./convertfix.sh slaset.f
./convertfix.sh slasq1.f
./convertfix.sh slasq2.f
./convertfix.sh slasq3.f
./convertfix.sh slasq4.f
./convertfix.sh slasq5.f
./convertfix.sh slasq6.f
./convertfix.sh slasr.f
./convertfix.sh slasrt.f
./convertfix.sh slassq.f
./convertfix.sh slasv2.f
./convertfix.sh slaswlq.f
./convertfix.sh slaswp.f
./convertfix.sh slasy2.f
./convertfix.sh sla_syamv.f
./convertfix.sh slasyf_aa.f
./convertfix.sh slasyf.f
./convertfix.sh slasyf_rk.f
./convertfix.sh slasyf_rook.f
./convertfix.sh sla_syrcond.f
./convertfix.sh sla_syrfsx_extended.f
./convertfix.sh sla_syrpvgrw.f
./convertfix.sh slatbs.f
./convertfix.sh slatdf.f
./convertfix.sh slatps.f
./convertfix.sh slatrd.f
./convertfix.sh slatrs.f
./convertfix.sh slatrz.f
./convertfix.sh slatsqr.f
./convertfix.sh slauu2.f
./convertfix.sh slauum.f
./convertfix.sh sla_wwaddw.f
./convertfix.sh snrm2.f
./convertfix.sh sopgtr.f
./convertfix.sh sopmtr.f
./convertfix.sh sorbdb1.f
./convertfix.sh sorbdb2.f
./convertfix.sh sorbdb3.f
./convertfix.sh sorbdb4.f
./convertfix.sh sorbdb5.f
./convertfix.sh sorbdb6.f
./convertfix.sh sorbdb.f
./convertfix.sh sorcsd2by1.f
./convertfix.sh sorcsd.f
./convertfix.sh sorg2l.f
./convertfix.sh sorg2r.f
./convertfix.sh sorgbr.f
./convertfix.sh sorghr.f
./convertfix.sh sorgl2.f
./convertfix.sh sorglq.f
./convertfix.sh sorgql.f
./convertfix.sh sorgqr.f
./convertfix.sh sorgr2.f
./convertfix.sh sorgrq.f
./convertfix.sh sorgtr.f
./convertfix.sh sorm22.f
./convertfix.sh sorm2l.f
./convertfix.sh sorm2r.f
./convertfix.sh sormbr.f
./convertfix.sh sormhr.f
./convertfix.sh sorml2.f
./convertfix.sh sormlq.f
./convertfix.sh sormql.f
./convertfix.sh sormqr.f
./convertfix.sh sormr2.f
./convertfix.sh sormr3.f
./convertfix.sh sormrq.f
./convertfix.sh sormrz.f
./convertfix.sh sormtr.f
./convertfix.sh spbcon.f
./convertfix.sh spbequ.f
./convertfix.sh spbrfs.f
./convertfix.sh spbstf.f
./convertfix.sh spbsv.f
./convertfix.sh spbsvx.f
./convertfix.sh spbtf2.f
./convertfix.sh spbtrf.f
./convertfix.sh spbtrs.f
./convertfix.sh spftrf.f
./convertfix.sh spftri.f
./convertfix.sh spftrs.f
./convertfix.sh spocon.f
./convertfix.sh spoequb.f
./convertfix.sh spoequ.f
./convertfix.sh sporfs.f
./convertfix.sh sporfsx.f
./convertfix.sh sposv.f
./convertfix.sh sposvx.f
./convertfix.sh sposvxx.f
./convertfix.sh spotf2.f
./convertfix.sh spotrf2.f
./convertfix.sh spotrf.f
./convertfix.sh spotri.f
./convertfix.sh spotrs.f
./convertfix.sh sppcon.f
./convertfix.sh sppequ.f
./convertfix.sh spprfs.f
./convertfix.sh sppsv.f
./convertfix.sh sppsvx.f
./convertfix.sh spptrf.f
./convertfix.sh spptri.f
./convertfix.sh spptrs.f
./convertfix.sh spstf2.f
./convertfix.sh spstrf.f
./convertfix.sh sptcon.f
./convertfix.sh spteqr.f
./convertfix.sh sptrfs.f
./convertfix.sh sptsv.f
./convertfix.sh sptsvx.f
./convertfix.sh spttrf.f
./convertfix.sh spttrs.f
./convertfix.sh sptts2.f
./convertfix.sh srot.f
./convertfix.sh srotg.f
./convertfix.sh srotm.f
./convertfix.sh srotmg.f
./convertfix.sh srscl.f
./convertfix.sh ssb2st_kernels.f
./convertfix.sh ssbev_2stage.f
./convertfix.sh ssbevd_2stage.f
./convertfix.sh ssbevd.f
./convertfix.sh ssbev.f
./convertfix.sh ssbevx_2stage.f
./convertfix.sh ssbevx.f
./convertfix.sh ssbgst.f
./convertfix.sh ssbgvd.f
./convertfix.sh ssbgv.f
./convertfix.sh ssbgvx.f
./convertfix.sh ssbmv.f
./convertfix.sh ssbtrd.f
./convertfix.sh sscal.f
./convertfix.sh ssfrk.f
./convertfix.sh sspcon.f
./convertfix.sh sspevd.f
./convertfix.sh sspev.f
./convertfix.sh sspevx.f
./convertfix.sh sspgst.f
./convertfix.sh sspgvd.f
./convertfix.sh sspgv.f
./convertfix.sh sspgvx.f
./convertfix.sh sspmv.f
./convertfix.sh sspr2.f
./convertfix.sh sspr.f
./convertfix.sh ssprfs.f
./convertfix.sh sspsv.f
./convertfix.sh sspsvx.f
./convertfix.sh ssptrd.f
./convertfix.sh ssptrf.f
./convertfix.sh ssptri.f
./convertfix.sh ssptrs.f
./convertfix.sh sstebz.f
./convertfix.sh sstedc.f
./convertfix.sh sstegr.f
./convertfix.sh sstein.f
./convertfix.sh sstemr.f
./convertfix.sh ssteqr.f
./convertfix.sh ssterf.f
./convertfix.sh sstevd.f
./convertfix.sh sstev.f
./convertfix.sh sstevr.f
./convertfix.sh sstevx.f
./convertfix.sh sswap.f
./convertfix.sh ssycon_3.f
./convertfix.sh ssycon.f
./convertfix.sh ssycon_rook.f
./convertfix.sh ssyconv.f
./convertfix.sh ssyconvf.f
./convertfix.sh ssyconvf_rook.f
./convertfix.sh ssyequb.f
./convertfix.sh ssyev_2stage.f
./convertfix.sh ssyevd_2stage.f
./convertfix.sh ssyevd.f
./convertfix.sh ssyev.f
./convertfix.sh ssyevr_2stage.f
./convertfix.sh ssyevr.f
./convertfix.sh ssyevx_2stage.f
./convertfix.sh ssyevx.f
./convertfix.sh ssygs2.f
./convertfix.sh ssygst.f
./convertfix.sh ssygv_2stage.f
./convertfix.sh ssygvd.f
./convertfix.sh ssygv.f
./convertfix.sh ssygvx.f
./convertfix.sh ssymm.f
./convertfix.sh ssymv.f
./convertfix.sh ssyr2.f
./convertfix.sh ssyr2k.f
./convertfix.sh ssyr.f
./convertfix.sh ssyrfs.f
./convertfix.sh ssyrfsx.f
./convertfix.sh ssyrk.f
./convertfix.sh ssysv_aa_2stage.f
./convertfix.sh ssysv_aa.f
./convertfix.sh ssysv.f
./convertfix.sh ssysv_rk.f
./convertfix.sh ssysv_rook.f
./convertfix.sh ssysvx.f
./convertfix.sh ssysvxx.f
./convertfix.sh ssyswapr.f
./convertfix.sh ssytd2.f
./convertfix.sh ssytf2.f
./convertfix.sh ssytf2_rk.f
./convertfix.sh ssytf2_rook.f
./convertfix.sh ssytrd_2stage.f
./convertfix.sh ssytrd.f
./convertfix.sh ssytrd_sy2sb.f
./convertfix.sh ssytrf_aa_2stage.f
./convertfix.sh ssytrf_aa.f
./convertfix.sh ssytrf.f
./convertfix.sh ssytrf_rk.f
./convertfix.sh ssytrf_rook.f
./convertfix.sh ssytri2.f
./convertfix.sh ssytri2x.f
./convertfix.sh ssytri_3.f
./convertfix.sh ssytri_3x.f
./convertfix.sh ssytri.f
./convertfix.sh ssytri_rook.f
./convertfix.sh ssytrs2.f
./convertfix.sh ssytrs_3.f
./convertfix.sh ssytrs_aa_2stage.f
./convertfix.sh ssytrs_aa.f
./convertfix.sh ssytrs.f
./convertfix.sh ssytrs_rook.f
./convertfix.sh stbcon.f
./convertfix.sh stbmv.f
./convertfix.sh stbrfs.f
./convertfix.sh stbsv.f
./convertfix.sh stbtrs.f
./convertfix.sh stfsm.f
./convertfix.sh stftri.f
./convertfix.sh stfttp.f
./convertfix.sh stfttr.f
./convertfix.sh stgevc.f
./convertfix.sh stgex2.f
./convertfix.sh stgexc.f
./convertfix.sh stgsen.f
./convertfix.sh stgsja.f
./convertfix.sh stgsna.f
./convertfix.sh stgsy2.f
./convertfix.sh stgsyl.f
./convertfix.sh stpcon.f
./convertfix.sh stplqt2.f
./convertfix.sh stplqt.f
./convertfix.sh stpmlqt.f
./convertfix.sh stpmqrt.f
./convertfix.sh stpmv.f
./convertfix.sh stpqrt2.f
./convertfix.sh stpqrt.f
./convertfix.sh stprfb.f
./convertfix.sh stprfs.f
./convertfix.sh stpsv.f
./convertfix.sh stptri.f
./convertfix.sh stptrs.f
./convertfix.sh stpttf.f
./convertfix.sh stpttr.f
./convertfix.sh strcon.f
./convertfix.sh strevc3.f
./convertfix.sh strevc.f
./convertfix.sh strexc.f
./convertfix.sh strmm.f
./convertfix.sh strmv.f
./convertfix.sh strrfs.f
./convertfix.sh strsen.f
./convertfix.sh strsm.f
./convertfix.sh strsna.f
./convertfix.sh strsv.f
./convertfix.sh strsyl.f
./convertfix.sh strti2.f
./convertfix.sh strtri.f
./convertfix.sh strtrs.f
./convertfix.sh strttf.f
./convertfix.sh strttp.f
./convertfix.sh stzrzf.f
./convertfix.sh xerbla_array.f
./convertfix.sh xerbla.f
./convertfix.sh zaxpy.f
./convertfix.sh zbbcsd.f
./convertfix.sh zbdsqr.f
./convertfix.sh zcgesv.f
./convertfix.sh zcopy.f
./convertfix.sh zcposv.f
./convertfix.sh zdotc.f
./convertfix.sh zdotu.f
./convertfix.sh zdrot.f
./convertfix.sh zdrscl.f
./convertfix.sh zdscal.f
./convertfix.sh zgbbrd.f
./convertfix.sh zgbcon.f
./convertfix.sh zgbequb.f
./convertfix.sh zgbequ.f
./convertfix.sh zgbmv.f
./convertfix.sh zgbrfs.f
./convertfix.sh zgbrfsx.f
./convertfix.sh zgbsv.f
./convertfix.sh zgbsvx.f
./convertfix.sh zgbsvxx.f
./convertfix.sh zgbtf2.f
./convertfix.sh zgbtrf.f
./convertfix.sh zgbtrs.f
./convertfix.sh zgebak.f
./convertfix.sh zgebal.f
./convertfix.sh zgebd2.f
./convertfix.sh zgebrd.f
./convertfix.sh zgecon.f
./convertfix.sh zgeequb.f
./convertfix.sh zgeequ.f
./convertfix.sh zgees.f
./convertfix.sh zgeesx.f
./convertfix.sh zgeev.f
./convertfix.sh zgeevx.f
./convertfix.sh zgehd2.f
./convertfix.sh zgehrd.f
./convertfix.sh zgejsv.f
./convertfix.sh zgelq2.f
./convertfix.sh zgelq.f
./convertfix.sh zgelqf.f
./convertfix.sh zgelqt3.f
./convertfix.sh zgelqt.f
./convertfix.sh zgelsd.f
./convertfix.sh zgels.f
./convertfix.sh zgelss.f
./convertfix.sh zgelsy.f
./convertfix.sh zgemlq.f
./convertfix.sh zgemlqt.f
./convertfix.sh zgemm.f
./convertfix.sh zgemqr.f
./convertfix.sh zgemqrt.f
./convertfix.sh zgemv.f
./convertfix.sh zgeql2.f
./convertfix.sh zgeqlf.f
./convertfix.sh zgeqp3.f
./convertfix.sh zgeqr2.f
./convertfix.sh zgeqr2p.f
./convertfix.sh zgeqr.f
./convertfix.sh zgeqrf.f
./convertfix.sh zgeqrfp.f
./convertfix.sh zgeqrt2.f
./convertfix.sh zgeqrt3.f
./convertfix.sh zgeqrt.f
./convertfix.sh zgerc.f
./convertfix.sh zgerfs.f
./convertfix.sh zgerfsx.f
./convertfix.sh zgerq2.f
./convertfix.sh zgerqf.f
./convertfix.sh zgeru.f
./convertfix.sh zgesc2.f
./convertfix.sh zgesdd.f
./convertfix.sh zgesvd.f
./convertfix.sh zgesvdx.f
./convertfix.sh zgesv.f
./convertfix.sh zgesvj.f
./convertfix.sh zgesvx.f
./convertfix.sh zgesvxx.f
./convertfix.sh zgetc2.f
./convertfix.sh zgetf2.f
./convertfix.sh zgetrf2.f
./convertfix.sh zgetrf.f
./convertfix.sh zgetri.f
./convertfix.sh zgetrs.f
./convertfix.sh zgetsls.f
./convertfix.sh zggbak.f
./convertfix.sh zggbal.f
./convertfix.sh zgges3.f
./convertfix.sh zgges.f
./convertfix.sh zggesx.f
./convertfix.sh zggev3.f
./convertfix.sh zggev.f
./convertfix.sh zggevx.f
./convertfix.sh zggglm.f
./convertfix.sh zgghd3.f
./convertfix.sh zgghrd.f
./convertfix.sh zgglse.f
./convertfix.sh zggqrf.f
./convertfix.sh zggrqf.f
./convertfix.sh zggsvd3.f
./convertfix.sh zggsvp3.f
./convertfix.sh zgsvj0.f
./convertfix.sh zgsvj1.f
./convertfix.sh zgtcon.f
./convertfix.sh zgtrfs.f
./convertfix.sh zgtsv.f
./convertfix.sh zgtsvx.f
./convertfix.sh zgttrf.f
./convertfix.sh zgttrs.f
./convertfix.sh zgtts2.f
./convertfix.sh zhb2st_kernels.f
./convertfix.sh zhbev_2stage.f
./convertfix.sh zhbevd_2stage.f
./convertfix.sh zhbevd.f
./convertfix.sh zhbev.f
./convertfix.sh zhbevx_2stage.f
./convertfix.sh zhbevx.f
./convertfix.sh zhbgst.f
./convertfix.sh zhbgvd.f
./convertfix.sh zhbgv.f
./convertfix.sh zhbgvx.f
./convertfix.sh zhbmv.f
./convertfix.sh zhbtrd.f
./convertfix.sh zhecon_3.f
./convertfix.sh zhecon.f
./convertfix.sh zhecon_rook.f
./convertfix.sh zheequb.f
./convertfix.sh zheev_2stage.f
./convertfix.sh zheevd_2stage.f
./convertfix.sh zheevd.f
./convertfix.sh zheev.f
./convertfix.sh zheevr_2stage.f
./convertfix.sh zheevr.f
./convertfix.sh zheevx_2stage.f
./convertfix.sh zheevx.f
./convertfix.sh zhegs2.f
./convertfix.sh zhegst.f
./convertfix.sh zhegv_2stage.f
./convertfix.sh zhegvd.f
./convertfix.sh zhegv.f
./convertfix.sh zhegvx.f
./convertfix.sh zhemm.f
./convertfix.sh zhemv.f
./convertfix.sh zher2.f
./convertfix.sh zher2k.f
./convertfix.sh zher.f
./convertfix.sh zherfs.f
./convertfix.sh zherfsx.f
./convertfix.sh zherk.f
./convertfix.sh zhesv_aa_2stage.f
./convertfix.sh zhesv_aa.f
./convertfix.sh zhesv.f
./convertfix.sh zhesv_rk.f
./convertfix.sh zhesv_rook.f
./convertfix.sh zhesvx.f
./convertfix.sh zhesvxx.f
./convertfix.sh zheswapr.f
./convertfix.sh zhetd2.f
./convertfix.sh zhetf2.f
./convertfix.sh zhetf2_rk.f
./convertfix.sh zhetf2_rook.f
./convertfix.sh zhetrd_2stage.f
./convertfix.sh zhetrd.f
./convertfix.sh zhetrd_he2hb.f
./convertfix.sh zhetrf_aa_2stage.f
./convertfix.sh zhetrf_aa.f
./convertfix.sh zhetrf.f
./convertfix.sh zhetrf_rk.f
./convertfix.sh zhetrf_rook.f
./convertfix.sh zhetri2.f
./convertfix.sh zhetri2x.f
./convertfix.sh zhetri_3.f
./convertfix.sh zhetri_3x.f
./convertfix.sh zhetri.f
./convertfix.sh zhetri_rook.f
./convertfix.sh zhetrs2.f
./convertfix.sh zhetrs_3.f
./convertfix.sh zhetrs_aa_2stage.f
./convertfix.sh zhetrs_aa.f
./convertfix.sh zhetrs.f
./convertfix.sh zhetrs_rook.f
./convertfix.sh zhfrk.f
./convertfix.sh zhgeqz.f
./convertfix.sh zhpcon.f
./convertfix.sh zhpevd.f
./convertfix.sh zhpev.f
./convertfix.sh zhpevx.f
./convertfix.sh zhpgst.f
./convertfix.sh zhpgvd.f
./convertfix.sh zhpgv.f
./convertfix.sh zhpgvx.f
./convertfix.sh zhpmv.f
./convertfix.sh zhpr2.f
./convertfix.sh zhpr.f
./convertfix.sh zhprfs.f
./convertfix.sh zhpsv.f
./convertfix.sh zhpsvx.f
./convertfix.sh zhptrd.f
./convertfix.sh zhptrf.f
./convertfix.sh zhptri.f
./convertfix.sh zhptrs.f
./convertfix.sh zhsein.f
./convertfix.sh zhseqr.f
./convertfix.sh zlabrd.f
./convertfix.sh zlacgv.f
./convertfix.sh zlacn2.f
./convertfix.sh zlacon.f
./convertfix.sh zlacp2.f
./convertfix.sh zlacpy.f
./convertfix.sh zlacrm.f
./convertfix.sh zlacrt.f
./convertfix.sh zladiv.f
./convertfix.sh zlaed0.f
./convertfix.sh zlaed7.f
./convertfix.sh zlaed8.f
./convertfix.sh zlaein.f
./convertfix.sh zlaesy.f
./convertfix.sh zlaev2.f
./convertfix.sh zlag2c.f
./convertfix.sh zla_gbamv.f
./convertfix.sh zla_gbrcond_c.f
./convertfix.sh zla_gbrcond_x.f
./convertfix.sh zla_gbrfsx_extended.f
./convertfix.sh zla_gbrpvgrw.f
./convertfix.sh zla_geamv.f
./convertfix.sh zla_gercond_c.f
./convertfix.sh zla_gercond_x.f
./convertfix.sh zla_gerfsx_extended.f
./convertfix.sh zla_gerpvgrw.f
./convertfix.sh zlags2.f
./convertfix.sh zlagtm.f
./convertfix.sh zla_heamv.f
./convertfix.sh zlahef_aa.f
./convertfix.sh zlahef.f
./convertfix.sh zlahef_rk.f
./convertfix.sh zlahef_rook.f
./convertfix.sh zla_hercond_c.f
./convertfix.sh zla_hercond_x.f
./convertfix.sh zla_herfsx_extended.f
./convertfix.sh zla_herpvgrw.f
./convertfix.sh zlahqr.f
./convertfix.sh zlahr2.f
./convertfix.sh zlaic1.f
./convertfix.sh zla_lin_berr.f
./convertfix.sh zlals0.f
./convertfix.sh zlalsa.f
./convertfix.sh zlalsd.f
./convertfix.sh zlamswlq.f
./convertfix.sh zlamtsqr.f
./convertfix.sh zlangb.f
./convertfix.sh zlange.f
./convertfix.sh zlangt.f
./convertfix.sh zlanhb.f
./convertfix.sh zlanhe.f
./convertfix.sh zlanhf.f
./convertfix.sh zlanhp.f
./convertfix.sh zlanhs.f
./convertfix.sh zlanht.f
./convertfix.sh zlansb.f
./convertfix.sh zlansp.f
./convertfix.sh zlansy.f
./convertfix.sh zlantb.f
./convertfix.sh zlantp.f
./convertfix.sh zlantr.f
./convertfix.sh zlapll.f
./convertfix.sh zlapmr.f
./convertfix.sh zlapmt.f
./convertfix.sh zla_porcond_c.f
./convertfix.sh zla_porcond_x.f
./convertfix.sh zla_porfsx_extended.f
./convertfix.sh zla_porpvgrw.f
./convertfix.sh zlaqgb.f
./convertfix.sh zlaqge.f
./convertfix.sh zlaqhb.f
./convertfix.sh zlaqhe.f
./convertfix.sh zlaqhp.f
./convertfix.sh zlaqp2.f
./convertfix.sh zlaqps.f
./convertfix.sh zlaqr0.f
./convertfix.sh zlaqr1.f
./convertfix.sh zlaqr2.f
./convertfix.sh zlaqr3.f
./convertfix.sh zlaqr4.f
./convertfix.sh zlaqr5.f
./convertfix.sh zlaqsb.f
./convertfix.sh zlaqsp.f
./convertfix.sh zlaqsy.f
./convertfix.sh zlar1v.f
./convertfix.sh zlar2v.f
./convertfix.sh zlarcm.f
./convertfix.sh zlarfb.f
./convertfix.sh zlarf.f
./convertfix.sh zlarfg.f
./convertfix.sh zlarfgp.f
./convertfix.sh zlarft.f
./convertfix.sh zlarfx.f
./convertfix.sh zlarfy.f
./convertfix.sh zlargv.f
./convertfix.sh zlarnv.f
./convertfix.sh zlarrv.f
./convertfix.sh zlarscl2.f
./convertfix.sh zlartg.f
./convertfix.sh zlartv.f
./convertfix.sh zlarzb.f
./convertfix.sh zlarz.f
./convertfix.sh zlarzt.f
./convertfix.sh zlascl2.f
./convertfix.sh zlascl.f
./convertfix.sh zlaset.f
./convertfix.sh zlasr.f
./convertfix.sh zlassq.f
./convertfix.sh zlaswlq.f
./convertfix.sh zlaswp.f
./convertfix.sh zla_syamv.f
./convertfix.sh zlasyf_aa.f
./convertfix.sh zlasyf.f
./convertfix.sh zlasyf_rk.f
./convertfix.sh zlasyf_rook.f
./convertfix.sh zla_syrcond_c.f
./convertfix.sh zla_syrcond_x.f
./convertfix.sh zla_syrfsx_extended.f
./convertfix.sh zla_syrpvgrw.f
./convertfix.sh zlat2c.f
./convertfix.sh zlatbs.f
./convertfix.sh zlatdf.f
./convertfix.sh zlatps.f
./convertfix.sh zlatrd.f
./convertfix.sh zlatrs.f
./convertfix.sh zlatrz.f
./convertfix.sh zlatsqr.f
./convertfix.sh zlauu2.f
./convertfix.sh zlauum.f
./convertfix.sh zla_wwaddw.f
./convertfix.sh zpbcon.f
./convertfix.sh zpbequ.f
./convertfix.sh zpbrfs.f
./convertfix.sh zpbstf.f
./convertfix.sh zpbsv.f
./convertfix.sh zpbsvx.f
./convertfix.sh zpbtf2.f
./convertfix.sh zpbtrf.f
./convertfix.sh zpbtrs.f
./convertfix.sh zpftrf.f
./convertfix.sh zpftri.f
./convertfix.sh zpftrs.f
./convertfix.sh zpocon.f
./convertfix.sh zpoequb.f
./convertfix.sh zpoequ.f
./convertfix.sh zporfs.f
./convertfix.sh zporfsx.f
./convertfix.sh zposv.f
./convertfix.sh zposvx.f
./convertfix.sh zposvxx.f
./convertfix.sh zpotf2.f
./convertfix.sh zpotrf2.f
./convertfix.sh zpotrf.f
./convertfix.sh zpotri.f
./convertfix.sh zpotrs.f
./convertfix.sh zppcon.f
./convertfix.sh zppequ.f
./convertfix.sh zpprfs.f
./convertfix.sh zppsv.f
./convertfix.sh zppsvx.f
./convertfix.sh zpptrf.f
./convertfix.sh zpptri.f
./convertfix.sh zpptrs.f
./convertfix.sh zpstf2.f
./convertfix.sh zpstrf.f
./convertfix.sh zptcon.f
./convertfix.sh zpteqr.f
./convertfix.sh zptrfs.f
./convertfix.sh zptsv.f
./convertfix.sh zptsvx.f
./convertfix.sh zpttrf.f
./convertfix.sh zpttrs.f
./convertfix.sh zptts2.f
./convertfix.sh zrot.f
./convertfix.sh zrotg.f
./convertfix.sh zscal.f
./convertfix.sh zspcon.f
./convertfix.sh zspmv.f
./convertfix.sh zspr.f
./convertfix.sh zsprfs.f
./convertfix.sh zspsv.f
./convertfix.sh zspsvx.f
./convertfix.sh zsptrf.f
./convertfix.sh zsptri.f
./convertfix.sh zsptrs.f
./convertfix.sh zstedc.f
./convertfix.sh zstegr.f
./convertfix.sh zstein.f
./convertfix.sh zstemr.f
./convertfix.sh zsteqr.f
./convertfix.sh zswap.f
./convertfix.sh zsycon_3.f
./convertfix.sh zsycon.f
./convertfix.sh zsycon_rook.f
./convertfix.sh zsyconv.f
./convertfix.sh zsyconvf.f
./convertfix.sh zsyconvf_rook.f
./convertfix.sh zsyequb.f
./convertfix.sh zsymm.f
./convertfix.sh zsymv.f
./convertfix.sh zsyr2k.f
./convertfix.sh zsyr.f
./convertfix.sh zsyrfs.f
./convertfix.sh zsyrfsx.f
./convertfix.sh zsyrk.f
./convertfix.sh zsysv_aa_2stage.f
./convertfix.sh zsysv_aa.f
./convertfix.sh zsysv.f
./convertfix.sh zsysv_rk.f
./convertfix.sh zsysv_rook.f
./convertfix.sh zsysvx.f
./convertfix.sh zsysvxx.f
./convertfix.sh zsyswapr.f
./convertfix.sh zsytf2.f
./convertfix.sh zsytf2_rk.f
./convertfix.sh zsytf2_rook.f
./convertfix.sh zsytrf_aa_2stage.f
./convertfix.sh zsytrf_aa.f
./convertfix.sh zsytrf.f
./convertfix.sh zsytrf_rk.f
./convertfix.sh zsytrf_rook.f
./convertfix.sh zsytri2.f
./convertfix.sh zsytri2x.f
./convertfix.sh zsytri_3.f
./convertfix.sh zsytri_3x.f
./convertfix.sh zsytri.f
./convertfix.sh zsytri_rook.f
./convertfix.sh zsytrs2.f
./convertfix.sh zsytrs_3.f
./convertfix.sh zsytrs_aa_2stage.f
./convertfix.sh zsytrs_aa.f
./convertfix.sh zsytrs.f
./convertfix.sh zsytrs_rook.f
./convertfix.sh ztbcon.f
./convertfix.sh ztbmv.f
./convertfix.sh ztbrfs.f
./convertfix.sh ztbsv.f
./convertfix.sh ztbtrs.f
./convertfix.sh ztfsm.f
./convertfix.sh ztftri.f
./convertfix.sh ztfttp.f
./convertfix.sh ztfttr.f
./convertfix.sh ztgevc.f
./convertfix.sh ztgex2.f
./convertfix.sh ztgexc.f
./convertfix.sh ztgsen.f
./convertfix.sh ztgsja.f
./convertfix.sh ztgsna.f
./convertfix.sh ztgsy2.f
./convertfix.sh ztgsyl.f
./convertfix.sh ztpcon.f
./convertfix.sh ztplqt2.f
./convertfix.sh ztplqt.f
./convertfix.sh ztpmlqt.f
./convertfix.sh ztpmqrt.f
./convertfix.sh ztpmv.f
./convertfix.sh ztpqrt2.f
./convertfix.sh ztpqrt.f
./convertfix.sh ztprfb.f
./convertfix.sh ztprfs.f
./convertfix.sh ztpsv.f
./convertfix.sh ztptri.f
./convertfix.sh ztptrs.f
./convertfix.sh ztpttf.f
./convertfix.sh ztpttr.f
./convertfix.sh ztrcon.f
./convertfix.sh ztrevc3.f
./convertfix.sh ztrevc.f
./convertfix.sh ztrexc.f
./convertfix.sh ztrmm.f
./convertfix.sh ztrmv.f
./convertfix.sh ztrrfs.f
./convertfix.sh ztrsen.f
./convertfix.sh ztrsm.f
./convertfix.sh ztrsna.f
./convertfix.sh ztrsv.f
./convertfix.sh ztrsyl.f
./convertfix.sh ztrti2.f
./convertfix.sh ztrtri.f
./convertfix.sh ztrtrs.f
./convertfix.sh ztrttf.f
./convertfix.sh ztrttp.f
./convertfix.sh ztzrzf.f
./convertfix.sh zunbdb1.f
./convertfix.sh zunbdb2.f
./convertfix.sh zunbdb3.f
./convertfix.sh zunbdb4.f
./convertfix.sh zunbdb5.f
./convertfix.sh zunbdb6.f
./convertfix.sh zunbdb.f
./convertfix.sh zuncsd2by1.f
./convertfix.sh zuncsd.f
./convertfix.sh zung2l.f
./convertfix.sh zung2r.f
./convertfix.sh zungbr.f
./convertfix.sh zunghr.f
./convertfix.sh zungl2.f
./convertfix.sh zunglq.f
./convertfix.sh zungql.f
./convertfix.sh zungqr.f
./convertfix.sh zungr2.f
./convertfix.sh zungrq.f
./convertfix.sh zungtr.f
./convertfix.sh zunm22.f
./convertfix.sh zunm2l.f
./convertfix.sh zunm2r.f
./convertfix.sh zunmbr.f
./convertfix.sh zunmhr.f
./convertfix.sh zunml2.f
./convertfix.sh zunmlq.f
./convertfix.sh zunmql.f
./convertfix.sh zunmqr.f
./convertfix.sh zunmr2.f
./convertfix.sh zunmr3.f
./convertfix.sh zunmrq.f
./convertfix.sh zunmrz.f
./convertfix.sh zunmtr.f
./convertfix.sh zupgtr.f
./convertfix.sh zupmtr.f
